# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feature_model.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'feature_model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66\x65\x61ture_model.proto\x12\x05model\"#\n\x07NaValue\x12\x0b\n\x03ori\x18\x01 \x01(\x01\x12\x0b\n\x03val\x18\x02 \x01(\x01\"Z\n\x07\x42inning\x12\x15\n\rbinning_split\x18\x01 \x03(\x01\x12\x0b\n\x03woe\x18\x02 \x03(\x01\x12\x0f\n\x07\x66\x65\x61ture\x18\x03 \x01(\t\x12\x1a\n\x02na\x18\x04 \x01(\x0b\x32\x0e.model.NaValue\"\x8f\x01\n\x08WOEModel\x12<\n\x0f\x66\x65\x61ture_binning\x18\x01 \x03(\x0b\x32#.model.WOEModel.FeatureBinningEntry\x1a\x45\n\x13\x46\x65\x61tureBinningEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.model.Binning:\x02\x38\x01\"1\n\nNormalizer\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x01(\t\x12\x12\n\nnorm_value\x18\x02 \x01(\x01\"7\n\x0eStandardScaler\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x01(\t\x12\t\n\x01u\x18\x02 \x01(\x01\x12\t\n\x01s\x18\x03 \x01(\x01\"\xb5\x01\n\x12NormalizationModel\x12\x0c\n\x04\x61xis\x18\x01 \x01(\x05\x12\x0c\n\x04norm\x18\x02 \x01(\t\x12=\n\nnormalizer\x18\x03 \x03(\x0b\x32).model.NormalizationModel.NormalizerEntry\x1a\x44\n\x0fNormalizerEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.model.Normalizer:\x02\x38\x01\"\xae\x01\n\x14StandardizationModel\x12H\n\x0fstandard_scaler\x18\x02 \x03(\x0b\x32/.model.StandardizationModel.StandardScalerEntry\x1aL\n\x13StandardScalerEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.model.StandardScaler:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feature_model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WOEMODEL_FEATUREBINNINGENTRY']._loaded_options = None
  _globals['_WOEMODEL_FEATUREBINNINGENTRY']._serialized_options = b'8\001'
  _globals['_NORMALIZATIONMODEL_NORMALIZERENTRY']._loaded_options = None
  _globals['_NORMALIZATIONMODEL_NORMALIZERENTRY']._serialized_options = b'8\001'
  _globals['_STANDARDIZATIONMODEL_STANDARDSCALERENTRY']._loaded_options = None
  _globals['_STANDARDIZATIONMODEL_STANDARDSCALERENTRY']._serialized_options = b'8\001'
  _globals['_NAVALUE']._serialized_start=30
  _globals['_NAVALUE']._serialized_end=65
  _globals['_BINNING']._serialized_start=67
  _globals['_BINNING']._serialized_end=157
  _globals['_WOEMODEL']._serialized_start=160
  _globals['_WOEMODEL']._serialized_end=303
  _globals['_WOEMODEL_FEATUREBINNINGENTRY']._serialized_start=234
  _globals['_WOEMODEL_FEATUREBINNINGENTRY']._serialized_end=303
  _globals['_NORMALIZER']._serialized_start=305
  _globals['_NORMALIZER']._serialized_end=354
  _globals['_STANDARDSCALER']._serialized_start=356
  _globals['_STANDARDSCALER']._serialized_end=411
  _globals['_NORMALIZATIONMODEL']._serialized_start=414
  _globals['_NORMALIZATIONMODEL']._serialized_end=595
  _globals['_NORMALIZATIONMODEL_NORMALIZERENTRY']._serialized_start=527
  _globals['_NORMALIZATIONMODEL_NORMALIZERENTRY']._serialized_end=595
  _globals['_STANDARDIZATIONMODEL']._serialized_start=598
  _globals['_STANDARDIZATIONMODEL']._serialized_end=772
  _globals['_STANDARDIZATIONMODEL_STANDARDSCALERENTRY']._serialized_start=696
  _globals['_STANDARDIZATIONMODEL_STANDARDSCALERENTRY']._serialized_end=772
# @@protoc_insertion_point(module_scope)
