# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feature_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='feature_model.proto',
  package='model',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x66\x65\x61ture_model.proto\x12\x05model\"#\n\x07NaValue\x12\x0b\n\x03ori\x18\x01 \x01(\x01\x12\x0b\n\x03val\x18\x02 \x01(\x01\"Z\n\x07\x42inning\x12\x15\n\rbinning_split\x18\x01 \x03(\x01\x12\x0b\n\x03woe\x18\x02 \x03(\x01\x12\x0f\n\x07\x66\x65\x61ture\x18\x03 \x01(\t\x12\x1a\n\x02na\x18\x04 \x01(\x0b\x32\x0e.model.NaValue\"\x8f\x01\n\x08WOEModel\x12<\n\x0f\x66\x65\x61ture_binning\x18\x01 \x03(\x0b\x32#.model.WOEModel.FeatureBinningEntry\x1a\x45\n\x13\x46\x65\x61tureBinningEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.model.Binning:\x02\x38\x01\"1\n\nNormalizer\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x01(\t\x12\x12\n\nnorm_value\x18\x02 \x01(\x01\"7\n\x0eStandardScaler\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x01(\t\x12\t\n\x01u\x18\x02 \x01(\x01\x12\t\n\x01s\x18\x03 \x01(\x01\"\xb5\x01\n\x12NormalizationModel\x12\x0c\n\x04\x61xis\x18\x01 \x01(\x05\x12\x0c\n\x04norm\x18\x02 \x01(\t\x12=\n\nnormalizer\x18\x03 \x03(\x0b\x32).model.NormalizationModel.NormalizerEntry\x1a\x44\n\x0fNormalizerEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.model.Normalizer:\x02\x38\x01\"\xae\x01\n\x14StandardizationModel\x12H\n\x0fstandard_scaler\x18\x02 \x03(\x0b\x32/.model.StandardizationModel.StandardScalerEntry\x1aL\n\x13StandardScalerEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.model.StandardScaler:\x02\x38\x01\x62\x06proto3'
)




_NAVALUE = _descriptor.Descriptor(
  name='NaValue',
  full_name='model.NaValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ori', full_name='model.NaValue.ori', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val', full_name='model.NaValue.val', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=65,
)


_BINNING = _descriptor.Descriptor(
  name='Binning',
  full_name='model.Binning',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='binning_split', full_name='model.Binning.binning_split', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='woe', full_name='model.Binning.woe', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature', full_name='model.Binning.feature', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='na', full_name='model.Binning.na', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=157,
)


_WOEMODEL_FEATUREBINNINGENTRY = _descriptor.Descriptor(
  name='FeatureBinningEntry',
  full_name='model.WOEModel.FeatureBinningEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='model.WOEModel.FeatureBinningEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='model.WOEModel.FeatureBinningEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=303,
)

_WOEMODEL = _descriptor.Descriptor(
  name='WOEModel',
  full_name='model.WOEModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_binning', full_name='model.WOEModel.feature_binning', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_WOEMODEL_FEATUREBINNINGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=303,
)


_NORMALIZER = _descriptor.Descriptor(
  name='Normalizer',
  full_name='model.Normalizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='model.Normalizer.feature', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='norm_value', full_name='model.Normalizer.norm_value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=354,
)


_STANDARDSCALER = _descriptor.Descriptor(
  name='StandardScaler',
  full_name='model.StandardScaler',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='model.StandardScaler.feature', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='u', full_name='model.StandardScaler.u', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s', full_name='model.StandardScaler.s', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=411,
)


_NORMALIZATIONMODEL_NORMALIZERENTRY = _descriptor.Descriptor(
  name='NormalizerEntry',
  full_name='model.NormalizationModel.NormalizerEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='model.NormalizationModel.NormalizerEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='model.NormalizationModel.NormalizerEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=595,
)

_NORMALIZATIONMODEL = _descriptor.Descriptor(
  name='NormalizationModel',
  full_name='model.NormalizationModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='axis', full_name='model.NormalizationModel.axis', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='norm', full_name='model.NormalizationModel.norm', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='normalizer', full_name='model.NormalizationModel.normalizer', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NORMALIZATIONMODEL_NORMALIZERENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=595,
)


_STANDARDIZATIONMODEL_STANDARDSCALERENTRY = _descriptor.Descriptor(
  name='StandardScalerEntry',
  full_name='model.StandardizationModel.StandardScalerEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='model.StandardizationModel.StandardScalerEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='model.StandardizationModel.StandardScalerEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=696,
  serialized_end=772,
)

_STANDARDIZATIONMODEL = _descriptor.Descriptor(
  name='StandardizationModel',
  full_name='model.StandardizationModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='standard_scaler', full_name='model.StandardizationModel.standard_scaler', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STANDARDIZATIONMODEL_STANDARDSCALERENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=772,
)

_BINNING.fields_by_name['na'].message_type = _NAVALUE
_WOEMODEL_FEATUREBINNINGENTRY.fields_by_name['value'].message_type = _BINNING
_WOEMODEL_FEATUREBINNINGENTRY.containing_type = _WOEMODEL
_WOEMODEL.fields_by_name['feature_binning'].message_type = _WOEMODEL_FEATUREBINNINGENTRY
_NORMALIZATIONMODEL_NORMALIZERENTRY.fields_by_name['value'].message_type = _NORMALIZER
_NORMALIZATIONMODEL_NORMALIZERENTRY.containing_type = _NORMALIZATIONMODEL
_NORMALIZATIONMODEL.fields_by_name['normalizer'].message_type = _NORMALIZATIONMODEL_NORMALIZERENTRY
_STANDARDIZATIONMODEL_STANDARDSCALERENTRY.fields_by_name['value'].message_type = _STANDARDSCALER
_STANDARDIZATIONMODEL_STANDARDSCALERENTRY.containing_type = _STANDARDIZATIONMODEL
_STANDARDIZATIONMODEL.fields_by_name['standard_scaler'].message_type = _STANDARDIZATIONMODEL_STANDARDSCALERENTRY
DESCRIPTOR.message_types_by_name['NaValue'] = _NAVALUE
DESCRIPTOR.message_types_by_name['Binning'] = _BINNING
DESCRIPTOR.message_types_by_name['WOEModel'] = _WOEMODEL
DESCRIPTOR.message_types_by_name['Normalizer'] = _NORMALIZER
DESCRIPTOR.message_types_by_name['StandardScaler'] = _STANDARDSCALER
DESCRIPTOR.message_types_by_name['NormalizationModel'] = _NORMALIZATIONMODEL
DESCRIPTOR.message_types_by_name['StandardizationModel'] = _STANDARDIZATIONMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NaValue = _reflection.GeneratedProtocolMessageType('NaValue', (_message.Message,), {
  'DESCRIPTOR' : _NAVALUE,
  '__module__' : 'feature_model_pb2'
  # @@protoc_insertion_point(class_scope:model.NaValue)
  })
_sym_db.RegisterMessage(NaValue)

Binning = _reflection.GeneratedProtocolMessageType('Binning', (_message.Message,), {
  'DESCRIPTOR' : _BINNING,
  '__module__' : 'feature_model_pb2'
  # @@protoc_insertion_point(class_scope:model.Binning)
  })
_sym_db.RegisterMessage(Binning)

WOEModel = _reflection.GeneratedProtocolMessageType('WOEModel', (_message.Message,), {

  'FeatureBinningEntry' : _reflection.GeneratedProtocolMessageType('FeatureBinningEntry', (_message.Message,), {
    'DESCRIPTOR' : _WOEMODEL_FEATUREBINNINGENTRY,
    '__module__' : 'feature_model_pb2'
    # @@protoc_insertion_point(class_scope:model.WOEModel.FeatureBinningEntry)
    })
  ,
  'DESCRIPTOR' : _WOEMODEL,
  '__module__' : 'feature_model_pb2'
  # @@protoc_insertion_point(class_scope:model.WOEModel)
  })
_sym_db.RegisterMessage(WOEModel)
_sym_db.RegisterMessage(WOEModel.FeatureBinningEntry)

Normalizer = _reflection.GeneratedProtocolMessageType('Normalizer', (_message.Message,), {
  'DESCRIPTOR' : _NORMALIZER,
  '__module__' : 'feature_model_pb2'
  # @@protoc_insertion_point(class_scope:model.Normalizer)
  })
_sym_db.RegisterMessage(Normalizer)

StandardScaler = _reflection.GeneratedProtocolMessageType('StandardScaler', (_message.Message,), {
  'DESCRIPTOR' : _STANDARDSCALER,
  '__module__' : 'feature_model_pb2'
  # @@protoc_insertion_point(class_scope:model.StandardScaler)
  })
_sym_db.RegisterMessage(StandardScaler)

NormalizationModel = _reflection.GeneratedProtocolMessageType('NormalizationModel', (_message.Message,), {

  'NormalizerEntry' : _reflection.GeneratedProtocolMessageType('NormalizerEntry', (_message.Message,), {
    'DESCRIPTOR' : _NORMALIZATIONMODEL_NORMALIZERENTRY,
    '__module__' : 'feature_model_pb2'
    # @@protoc_insertion_point(class_scope:model.NormalizationModel.NormalizerEntry)
    })
  ,
  'DESCRIPTOR' : _NORMALIZATIONMODEL,
  '__module__' : 'feature_model_pb2'
  # @@protoc_insertion_point(class_scope:model.NormalizationModel)
  })
_sym_db.RegisterMessage(NormalizationModel)
_sym_db.RegisterMessage(NormalizationModel.NormalizerEntry)

StandardizationModel = _reflection.GeneratedProtocolMessageType('StandardizationModel', (_message.Message,), {

  'StandardScalerEntry' : _reflection.GeneratedProtocolMessageType('StandardScalerEntry', (_message.Message,), {
    'DESCRIPTOR' : _STANDARDIZATIONMODEL_STANDARDSCALERENTRY,
    '__module__' : 'feature_model_pb2'
    # @@protoc_insertion_point(class_scope:model.StandardizationModel.StandardScalerEntry)
    })
  ,
  'DESCRIPTOR' : _STANDARDIZATIONMODEL,
  '__module__' : 'feature_model_pb2'
  # @@protoc_insertion_point(class_scope:model.StandardizationModel)
  })
_sym_db.RegisterMessage(StandardizationModel)
_sym_db.RegisterMessage(StandardizationModel.StandardScalerEntry)


_WOEMODEL_FEATUREBINNINGENTRY._options = None
_NORMALIZATIONMODEL_NORMALIZERENTRY._options = None
_STANDARDIZATIONMODEL_STANDARDSCALERENTRY._options = None
# @@protoc_insertion_point(module_scope)
