# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tree_model.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'tree_model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10tree_model.proto\x12\x05model\"\x84\x01\n\tSplitInfo\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x12\x13\n\x0b\x66\x65\x61ture_idx\x18\x02 \x01(\x05\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x03 \x01(\t\x12\x13\n\x0bis_category\x18\x04 \x01(\x08\x12\x13\n\x0bsplit_point\x18\x05 \x01(\x01\x12\x10\n\x08left_cat\x18\x06 \x03(\x01\"\xa6\x01\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\x05\x12\x14\n\x0cleft_node_id\x18\x03 \x01(\t\x12\x15\n\rright_node_id\x18\x04 \x01(\t\x12$\n\nsplit_info\x18\x05 \x01(\x0b\x32\x10.model.SplitInfo\x12\x0f\n\x07is_leaf\x18\x06 \x01(\x08\x12\x0e\n\x06weight\x18\x07 \x01(\x01\x12\x0f\n\x07linkage\x18\x08 \x01(\t\"\xa4\x01\n\x04Tree\x12\x10\n\x08party_id\x18\x01 \x01(\t\x12\x12\n\ntree_index\x18\x02 \x01(\x05\x12\x14\n\x0croot_node_id\x18\x03 \x01(\t\x12%\n\x05nodes\x18\x04 \x03(\x0b\x32\x16.model.Tree.NodesEntry\x1a\x39\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.model.Node:\x02\x38\x01\"\"\n\nNodeIdList\x12\x14\n\x0cnode_id_list\x18\x01 \x03(\t\"\xa1\x02\n\x0cXGBoostModel\x12\x19\n\x11suggest_threshold\x18\x01 \x01(\x01\x12\n\n\x02lr\x18\x02 \x03(\x01\x12\x11\n\tmax_depth\x18\x03 \x03(\x05\x12\x1a\n\x05trees\x18\x04 \x03(\x0b\x32\x0b.model.Tree\x12\x0f\n\x07version\x18\x05 \x01(\t\x12\x13\n\x0bloss_method\x18\x06 \x01(\t\x12\x11\n\tnum_trees\x18\x07 \x01(\x05\x12;\n\rnode_id_group\x18\x08 \x03(\x0b\x32$.model.XGBoostModel.NodeIdGroupEntry\x1a\x45\n\x10NodeIdGroupEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.model.NodeIdList:\x02\x38\x01\"r\n\tNodeModel\x12*\n\x05nodes\x18\x01 \x03(\x0b\x32\x1b.model.NodeModel.NodesEntry\x1a\x39\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.model.Node:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tree_model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TREE_NODESENTRY']._loaded_options = None
  _globals['_TREE_NODESENTRY']._serialized_options = b'8\001'
  _globals['_XGBOOSTMODEL_NODEIDGROUPENTRY']._loaded_options = None
  _globals['_XGBOOSTMODEL_NODEIDGROUPENTRY']._serialized_options = b'8\001'
  _globals['_NODEMODEL_NODESENTRY']._loaded_options = None
  _globals['_NODEMODEL_NODESENTRY']._serialized_options = b'8\001'
  _globals['_SPLITINFO']._serialized_start=28
  _globals['_SPLITINFO']._serialized_end=160
  _globals['_NODE']._serialized_start=163
  _globals['_NODE']._serialized_end=329
  _globals['_TREE']._serialized_start=332
  _globals['_TREE']._serialized_end=496
  _globals['_TREE_NODESENTRY']._serialized_start=439
  _globals['_TREE_NODESENTRY']._serialized_end=496
  _globals['_NODEIDLIST']._serialized_start=498
  _globals['_NODEIDLIST']._serialized_end=532
  _globals['_XGBOOSTMODEL']._serialized_start=535
  _globals['_XGBOOSTMODEL']._serialized_end=824
  _globals['_XGBOOSTMODEL_NODEIDGROUPENTRY']._serialized_start=755
  _globals['_XGBOOSTMODEL_NODEIDGROUPENTRY']._serialized_end=824
  _globals['_NODEMODEL']._serialized_start=826
  _globals['_NODEMODEL']._serialized_end=940
  _globals['_NODEMODEL_NODESENTRY']._serialized_start=439
  _globals['_NODEMODEL_NODESENTRY']._serialized_end=496
# @@protoc_insertion_point(module_scope)
