# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tree_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tree_model.proto',
  package='model',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10tree_model.proto\x12\x05model\"\x84\x01\n\tSplitInfo\x12\x10\n\x08owner_id\x18\x01 \x01(\t\x12\x13\n\x0b\x66\x65\x61ture_idx\x18\x02 \x01(\x05\x12\x14\n\x0c\x66\x65\x61ture_name\x18\x03 \x01(\t\x12\x13\n\x0bis_category\x18\x04 \x01(\x08\x12\x13\n\x0bsplit_point\x18\x05 \x01(\x01\x12\x10\n\x08left_cat\x18\x06 \x03(\x01\"\xa6\x01\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\x05\x12\x14\n\x0cleft_node_id\x18\x03 \x01(\t\x12\x15\n\rright_node_id\x18\x04 \x01(\t\x12$\n\nsplit_info\x18\x05 \x01(\x0b\x32\x10.model.SplitInfo\x12\x0f\n\x07is_leaf\x18\x06 \x01(\x08\x12\x0e\n\x06weight\x18\x07 \x01(\x01\x12\x0f\n\x07linkage\x18\x08 \x01(\t\"\xa4\x01\n\x04Tree\x12\x10\n\x08party_id\x18\x01 \x01(\t\x12\x12\n\ntree_index\x18\x02 \x01(\x05\x12\x14\n\x0croot_node_id\x18\x03 \x01(\t\x12%\n\x05nodes\x18\x04 \x03(\x0b\x32\x16.model.Tree.NodesEntry\x1a\x39\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.model.Node:\x02\x38\x01\"\"\n\nNodeIdList\x12\x14\n\x0cnode_id_list\x18\x01 \x03(\t\"\xa1\x02\n\x0cXGBoostModel\x12\x19\n\x11suggest_threshold\x18\x01 \x01(\x01\x12\n\n\x02lr\x18\x02 \x03(\x01\x12\x11\n\tmax_depth\x18\x03 \x03(\x05\x12\x1a\n\x05trees\x18\x04 \x03(\x0b\x32\x0b.model.Tree\x12\x0f\n\x07version\x18\x05 \x01(\t\x12\x13\n\x0bloss_method\x18\x06 \x01(\t\x12\x11\n\tnum_trees\x18\x07 \x01(\x05\x12;\n\rnode_id_group\x18\x08 \x03(\x0b\x32$.model.XGBoostModel.NodeIdGroupEntry\x1a\x45\n\x10NodeIdGroupEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.model.NodeIdList:\x02\x38\x01\"r\n\tNodeModel\x12*\n\x05nodes\x18\x01 \x03(\x0b\x32\x1b.model.NodeModel.NodesEntry\x1a\x39\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.model.Node:\x02\x38\x01\x62\x06proto3'
)




_SPLITINFO = _descriptor.Descriptor(
  name='SplitInfo',
  full_name='model.SplitInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner_id', full_name='model.SplitInfo.owner_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature_idx', full_name='model.SplitInfo.feature_idx', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature_name', full_name='model.SplitInfo.feature_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_category', full_name='model.SplitInfo.is_category', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='split_point', full_name='model.SplitInfo.split_point', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='left_cat', full_name='model.SplitInfo.left_cat', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=160,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='model.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='model.Node.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth', full_name='model.Node.depth', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='left_node_id', full_name='model.Node.left_node_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_node_id', full_name='model.Node.right_node_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='split_info', full_name='model.Node.split_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_leaf', full_name='model.Node.is_leaf', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight', full_name='model.Node.weight', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linkage', full_name='model.Node.linkage', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=329,
)


_TREE_NODESENTRY = _descriptor.Descriptor(
  name='NodesEntry',
  full_name='model.Tree.NodesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='model.Tree.NodesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='model.Tree.NodesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=496,
)

_TREE = _descriptor.Descriptor(
  name='Tree',
  full_name='model.Tree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='party_id', full_name='model.Tree.party_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tree_index', full_name='model.Tree.tree_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='root_node_id', full_name='model.Tree.root_node_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='model.Tree.nodes', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TREE_NODESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=496,
)


_NODEIDLIST = _descriptor.Descriptor(
  name='NodeIdList',
  full_name='model.NodeIdList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id_list', full_name='model.NodeIdList.node_id_list', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=532,
)


_XGBOOSTMODEL_NODEIDGROUPENTRY = _descriptor.Descriptor(
  name='NodeIdGroupEntry',
  full_name='model.XGBoostModel.NodeIdGroupEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='model.XGBoostModel.NodeIdGroupEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='model.XGBoostModel.NodeIdGroupEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=755,
  serialized_end=824,
)

_XGBOOSTMODEL = _descriptor.Descriptor(
  name='XGBoostModel',
  full_name='model.XGBoostModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='suggest_threshold', full_name='model.XGBoostModel.suggest_threshold', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lr', full_name='model.XGBoostModel.lr', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_depth', full_name='model.XGBoostModel.max_depth', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trees', full_name='model.XGBoostModel.trees', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='model.XGBoostModel.version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loss_method', full_name='model.XGBoostModel.loss_method', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_trees', full_name='model.XGBoostModel.num_trees', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_id_group', full_name='model.XGBoostModel.node_id_group', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_XGBOOSTMODEL_NODEIDGROUPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=824,
)


_NODEMODEL_NODESENTRY = _descriptor.Descriptor(
  name='NodesEntry',
  full_name='model.NodeModel.NodesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='model.NodeModel.NodesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='model.NodeModel.NodesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=496,
)

_NODEMODEL = _descriptor.Descriptor(
  name='NodeModel',
  full_name='model.NodeModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='model.NodeModel.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NODEMODEL_NODESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=826,
  serialized_end=940,
)

_NODE.fields_by_name['split_info'].message_type = _SPLITINFO
_TREE_NODESENTRY.fields_by_name['value'].message_type = _NODE
_TREE_NODESENTRY.containing_type = _TREE
_TREE.fields_by_name['nodes'].message_type = _TREE_NODESENTRY
_XGBOOSTMODEL_NODEIDGROUPENTRY.fields_by_name['value'].message_type = _NODEIDLIST
_XGBOOSTMODEL_NODEIDGROUPENTRY.containing_type = _XGBOOSTMODEL
_XGBOOSTMODEL.fields_by_name['trees'].message_type = _TREE
_XGBOOSTMODEL.fields_by_name['node_id_group'].message_type = _XGBOOSTMODEL_NODEIDGROUPENTRY
_NODEMODEL_NODESENTRY.fields_by_name['value'].message_type = _NODE
_NODEMODEL_NODESENTRY.containing_type = _NODEMODEL
_NODEMODEL.fields_by_name['nodes'].message_type = _NODEMODEL_NODESENTRY
DESCRIPTOR.message_types_by_name['SplitInfo'] = _SPLITINFO
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Tree'] = _TREE
DESCRIPTOR.message_types_by_name['NodeIdList'] = _NODEIDLIST
DESCRIPTOR.message_types_by_name['XGBoostModel'] = _XGBOOSTMODEL
DESCRIPTOR.message_types_by_name['NodeModel'] = _NODEMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SplitInfo = _reflection.GeneratedProtocolMessageType('SplitInfo', (_message.Message,), {
  'DESCRIPTOR' : _SPLITINFO,
  '__module__' : 'tree_model_pb2'
  # @@protoc_insertion_point(class_scope:model.SplitInfo)
  })
_sym_db.RegisterMessage(SplitInfo)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'tree_model_pb2'
  # @@protoc_insertion_point(class_scope:model.Node)
  })
_sym_db.RegisterMessage(Node)

Tree = _reflection.GeneratedProtocolMessageType('Tree', (_message.Message,), {

  'NodesEntry' : _reflection.GeneratedProtocolMessageType('NodesEntry', (_message.Message,), {
    'DESCRIPTOR' : _TREE_NODESENTRY,
    '__module__' : 'tree_model_pb2'
    # @@protoc_insertion_point(class_scope:model.Tree.NodesEntry)
    })
  ,
  'DESCRIPTOR' : _TREE,
  '__module__' : 'tree_model_pb2'
  # @@protoc_insertion_point(class_scope:model.Tree)
  })
_sym_db.RegisterMessage(Tree)
_sym_db.RegisterMessage(Tree.NodesEntry)

NodeIdList = _reflection.GeneratedProtocolMessageType('NodeIdList', (_message.Message,), {
  'DESCRIPTOR' : _NODEIDLIST,
  '__module__' : 'tree_model_pb2'
  # @@protoc_insertion_point(class_scope:model.NodeIdList)
  })
_sym_db.RegisterMessage(NodeIdList)

XGBoostModel = _reflection.GeneratedProtocolMessageType('XGBoostModel', (_message.Message,), {

  'NodeIdGroupEntry' : _reflection.GeneratedProtocolMessageType('NodeIdGroupEntry', (_message.Message,), {
    'DESCRIPTOR' : _XGBOOSTMODEL_NODEIDGROUPENTRY,
    '__module__' : 'tree_model_pb2'
    # @@protoc_insertion_point(class_scope:model.XGBoostModel.NodeIdGroupEntry)
    })
  ,
  'DESCRIPTOR' : _XGBOOSTMODEL,
  '__module__' : 'tree_model_pb2'
  # @@protoc_insertion_point(class_scope:model.XGBoostModel)
  })
_sym_db.RegisterMessage(XGBoostModel)
_sym_db.RegisterMessage(XGBoostModel.NodeIdGroupEntry)

NodeModel = _reflection.GeneratedProtocolMessageType('NodeModel', (_message.Message,), {

  'NodesEntry' : _reflection.GeneratedProtocolMessageType('NodesEntry', (_message.Message,), {
    'DESCRIPTOR' : _NODEMODEL_NODESENTRY,
    '__module__' : 'tree_model_pb2'
    # @@protoc_insertion_point(class_scope:model.NodeModel.NodesEntry)
    })
  ,
  'DESCRIPTOR' : _NODEMODEL,
  '__module__' : 'tree_model_pb2'
  # @@protoc_insertion_point(class_scope:model.NodeModel)
  })
_sym_db.RegisterMessage(NodeModel)
_sym_db.RegisterMessage(NodeModel.NodesEntry)


_TREE_NODESENTRY._options = None
_XGBOOSTMODEL_NODEIDGROUPENTRY._options = None
_NODEMODEL_NODESENTRY._options = None
# @@protoc_insertion_point(module_scope)
