# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commu.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63ommu.proto\x12\x05\x63ommu\")\n\x0bPostRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x1c\n\x0cPostResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x62\x06proto3')



_POSTREQUEST = DESCRIPTOR.message_types_by_name['PostRequest']
_POSTRESPONSE = DESCRIPTOR.message_types_by_name['PostResponse']
PostRequest = _reflection.GeneratedProtocolMessageType('PostRequest', (_message.Message,), {
  'DESCRIPTOR' : _POSTREQUEST,
  '__module__' : 'commu_pb2'
  # @@protoc_insertion_point(class_scope:commu.PostRequest)
  })
_sym_db.RegisterMessage(PostRequest)

PostResponse = _reflection.GeneratedProtocolMessageType('PostResponse', (_message.Message,), {
  'DESCRIPTOR' : _POSTRESPONSE,
  '__module__' : 'commu_pb2'
  # @@protoc_insertion_point(class_scope:commu.PostResponse)
  })
_sym_db.RegisterMessage(PostResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSTREQUEST._serialized_start=22
  _POSTREQUEST._serialized_end=63
  _POSTRESPONSE._serialized_start=65
  _POSTRESPONSE._serialized_end=93
# @@protoc_insertion_point(module_scope)
