# Copyright 2022 The XFL Authors. All rights reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commu_pb2 as commu__pb2
import status_pb2 as status__pb2
import control_pb2 as control__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scheduler.proto',
  package='scheduler',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fscheduler.proto\x12\tscheduler\x1a\x0b\x63ommu.proto\x1a\x0cstatus.proto\x1a\rcontrol.proto\"3\n\x10GetConfigRequest\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"Q\n\x11GetConfigResponse\x12\r\n\x05jobId\x18\x01 \x01(\x05\x12\x0e\n\x06\x63onfig\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t\"t\n\rDefaultConfig\x12\x34\n\x06\x63onfig\x18\x01 \x03(\x0b\x32$.scheduler.DefaultConfig.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x19\n\x17GetAlgorithmListRequest\"\xe7\x01\n\x18GetAlgorithmListResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x15\n\ralgorithmList\x18\x02 \x03(\t\x12S\n\x10\x64\x65\x66\x61ultConfigMap\x18\x03 \x03(\x0b\x32\x39.scheduler.GetAlgorithmListResponse.DefaultConfigMapEntry\x1aQ\n\x15\x44\x65\x66\x61ultConfigMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.scheduler.DefaultConfig:\x02\x38\x01\x32\xe4\x02\n\tScheduler\x12H\n\tgetConfig\x12\x1b.scheduler.GetConfigRequest\x1a\x1c.scheduler.GetConfigResponse\"\x00\x12\x33\n\x04post\x12\x12.commu.PostRequest\x1a\x13.commu.PostResponse\"\x00(\x01\x12>\n\x07\x63ontrol\x12\x17.control.ControlRequest\x1a\x18.control.ControlResponse\"\x00\x12\x39\n\x06status\x12\x15.status.StatusRequest\x1a\x16.status.StatusResponse\"\x00\x12]\n\x10getAlgorithmList\x12\".scheduler.GetAlgorithmListRequest\x1a#.scheduler.GetAlgorithmListResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[commu__pb2.DESCRIPTOR,status__pb2.DESCRIPTOR,control__pb2.DESCRIPTOR,])




_GETCONFIGREQUEST = _descriptor.Descriptor(
  name='GetConfigRequest',
  full_name='scheduler.GetConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeId', full_name='scheduler.GetConfigRequest.nodeId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='scheduler.GetConfigRequest.message', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=123,
)


_GETCONFIGRESPONSE = _descriptor.Descriptor(
  name='GetConfigResponse',
  full_name='scheduler.GetConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobId', full_name='scheduler.GetConfigResponse.jobId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='scheduler.GetConfigResponse.config', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='scheduler.GetConfigResponse.code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='scheduler.GetConfigResponse.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=206,
)


_DEFAULTCONFIG_CONFIGENTRY = _descriptor.Descriptor(
  name='ConfigEntry',
  full_name='scheduler.DefaultConfig.ConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='scheduler.DefaultConfig.ConfigEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='scheduler.DefaultConfig.ConfigEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=324,
)

_DEFAULTCONFIG = _descriptor.Descriptor(
  name='DefaultConfig',
  full_name='scheduler.DefaultConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='scheduler.DefaultConfig.config', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DEFAULTCONFIG_CONFIGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=324,
)


_GETALGORITHMLISTREQUEST = _descriptor.Descriptor(
  name='GetAlgorithmListRequest',
  full_name='scheduler.GetAlgorithmListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=351,
)


_GETALGORITHMLISTRESPONSE_DEFAULTCONFIGMAPENTRY = _descriptor.Descriptor(
  name='DefaultConfigMapEntry',
  full_name='scheduler.GetAlgorithmListResponse.DefaultConfigMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='scheduler.GetAlgorithmListResponse.DefaultConfigMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='scheduler.GetAlgorithmListResponse.DefaultConfigMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=585,
)

_GETALGORITHMLISTRESPONSE = _descriptor.Descriptor(
  name='GetAlgorithmListResponse',
  full_name='scheduler.GetAlgorithmListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='scheduler.GetAlgorithmListResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithmList', full_name='scheduler.GetAlgorithmListResponse.algorithmList', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='defaultConfigMap', full_name='scheduler.GetAlgorithmListResponse.defaultConfigMap', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GETALGORITHMLISTRESPONSE_DEFAULTCONFIGMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=585,
)

_DEFAULTCONFIG_CONFIGENTRY.containing_type = _DEFAULTCONFIG
_DEFAULTCONFIG.fields_by_name['config'].message_type = _DEFAULTCONFIG_CONFIGENTRY
_GETALGORITHMLISTRESPONSE_DEFAULTCONFIGMAPENTRY.fields_by_name['value'].message_type = _DEFAULTCONFIG
_GETALGORITHMLISTRESPONSE_DEFAULTCONFIGMAPENTRY.containing_type = _GETALGORITHMLISTRESPONSE
_GETALGORITHMLISTRESPONSE.fields_by_name['defaultConfigMap'].message_type = _GETALGORITHMLISTRESPONSE_DEFAULTCONFIGMAPENTRY
DESCRIPTOR.message_types_by_name['GetConfigRequest'] = _GETCONFIGREQUEST
DESCRIPTOR.message_types_by_name['GetConfigResponse'] = _GETCONFIGRESPONSE
DESCRIPTOR.message_types_by_name['DefaultConfig'] = _DEFAULTCONFIG
DESCRIPTOR.message_types_by_name['GetAlgorithmListRequest'] = _GETALGORITHMLISTREQUEST
DESCRIPTOR.message_types_by_name['GetAlgorithmListResponse'] = _GETALGORITHMLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetConfigRequest = _reflection.GeneratedProtocolMessageType('GetConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCONFIGREQUEST,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.GetConfigRequest)
  })
_sym_db.RegisterMessage(GetConfigRequest)

GetConfigResponse = _reflection.GeneratedProtocolMessageType('GetConfigResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCONFIGRESPONSE,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.GetConfigResponse)
  })
_sym_db.RegisterMessage(GetConfigResponse)

DefaultConfig = _reflection.GeneratedProtocolMessageType('DefaultConfig', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _DEFAULTCONFIG_CONFIGENTRY,
    '__module__' : 'scheduler_pb2'
    # @@protoc_insertion_point(class_scope:scheduler.DefaultConfig.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _DEFAULTCONFIG,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.DefaultConfig)
  })
_sym_db.RegisterMessage(DefaultConfig)
_sym_db.RegisterMessage(DefaultConfig.ConfigEntry)

GetAlgorithmListRequest = _reflection.GeneratedProtocolMessageType('GetAlgorithmListRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALGORITHMLISTREQUEST,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.GetAlgorithmListRequest)
  })
_sym_db.RegisterMessage(GetAlgorithmListRequest)

GetAlgorithmListResponse = _reflection.GeneratedProtocolMessageType('GetAlgorithmListResponse', (_message.Message,), {

  'DefaultConfigMapEntry' : _reflection.GeneratedProtocolMessageType('DefaultConfigMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETALGORITHMLISTRESPONSE_DEFAULTCONFIGMAPENTRY,
    '__module__' : 'scheduler_pb2'
    # @@protoc_insertion_point(class_scope:scheduler.GetAlgorithmListResponse.DefaultConfigMapEntry)
    })
  ,
  'DESCRIPTOR' : _GETALGORITHMLISTRESPONSE,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.GetAlgorithmListResponse)
  })
_sym_db.RegisterMessage(GetAlgorithmListResponse)
_sym_db.RegisterMessage(GetAlgorithmListResponse.DefaultConfigMapEntry)


_DEFAULTCONFIG_CONFIGENTRY._options = None
_GETALGORITHMLISTRESPONSE_DEFAULTCONFIGMAPENTRY._options = None

_SCHEDULER = _descriptor.ServiceDescriptor(
  name='Scheduler',
  full_name='scheduler.Scheduler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=588,
  serialized_end=944,
  methods=[
  _descriptor.MethodDescriptor(
    name='getConfig',
    full_name='scheduler.Scheduler.getConfig',
    index=0,
    containing_service=None,
    input_type=_GETCONFIGREQUEST,
    output_type=_GETCONFIGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='post',
    full_name='scheduler.Scheduler.post',
    index=1,
    containing_service=None,
    input_type=commu__pb2._POSTREQUEST,
    output_type=commu__pb2._POSTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='control',
    full_name='scheduler.Scheduler.control',
    index=2,
    containing_service=None,
    input_type=control__pb2._CONTROLREQUEST,
    output_type=control__pb2._CONTROLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='status',
    full_name='scheduler.Scheduler.status',
    index=3,
    containing_service=None,
    input_type=status__pb2._STATUSREQUEST,
    output_type=status__pb2._STATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getAlgorithmList',
    full_name='scheduler.Scheduler.getAlgorithmList',
    index=4,
    containing_service=None,
    input_type=_GETALGORITHMLISTREQUEST,
    output_type=_GETALGORITHMLISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULER)

DESCRIPTOR.services_by_name['Scheduler'] = _SCHEDULER

# @@protoc_insertion_point(module_scope)
