# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstatus.proto\x12\x06status\"&\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1e\n\rStatusRequest\x12\r\n\x05jobId\x18\x01 \x01(\x05\"\x97\x02\n\x0eStatusResponse\x12\r\n\x05jobId\x18\x01 \x01(\x05\x12!\n\tjobStatus\x18\x02 \x01(\x0b\x32\x0e.status.Status\x12\'\n\x0fschedulerStatus\x18\x03 \x01(\x0b\x32\x0e.status.Status\x12@\n\rtrainerStatus\x18\x04 \x03(\x0b\x32).status.StatusResponse.TrainerStatusEntry\x12\x11\n\tstartTime\x18\x05 \x01(\x05\x12\x0f\n\x07\x65ndTime\x18\x06 \x01(\x05\x1a\x44\n\x12TrainerStatusEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.status.Status:\x02\x38\x01*m\n\nStatusEnum\x12\n\n\x06STATUS\x10\x00\x12\x08\n\x04IDLE\x10\x01\x12\x0c\n\x08TRAINING\x10\x02\x12\x0e\n\nSUCCESSFUL\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x12\x0f\n\x0bSTART_TRAIN\x10\x05\x12\x0e\n\nSTOP_TRAIN\x10\x06\x62\x06proto3')

_STATUSENUM = DESCRIPTOR.enum_types_by_name['StatusEnum']
StatusEnum = enum_type_wrapper.EnumTypeWrapper(_STATUSENUM)
STATUS = 0
IDLE = 1
TRAINING = 2
SUCCESSFUL = 3
FAILED = 4
START_TRAIN = 5
STOP_TRAIN = 6


_STATUS = DESCRIPTOR.message_types_by_name['Status']
_STATUSREQUEST = DESCRIPTOR.message_types_by_name['StatusRequest']
_STATUSRESPONSE = DESCRIPTOR.message_types_by_name['StatusResponse']
_STATUSRESPONSE_TRAINERSTATUSENTRY = _STATUSRESPONSE.nested_types_by_name['TrainerStatusEntry']
Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'status_pb2'
  # @@protoc_insertion_point(class_scope:status.Status)
  })
_sym_db.RegisterMessage(Status)

StatusRequest = _reflection.GeneratedProtocolMessageType('StatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATUSREQUEST,
  '__module__' : 'status_pb2'
  # @@protoc_insertion_point(class_scope:status.StatusRequest)
  })
_sym_db.RegisterMessage(StatusRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {

  'TrainerStatusEntry' : _reflection.GeneratedProtocolMessageType('TrainerStatusEntry', (_message.Message,), {
    'DESCRIPTOR' : _STATUSRESPONSE_TRAINERSTATUSENTRY,
    '__module__' : 'status_pb2'
    # @@protoc_insertion_point(class_scope:status.StatusResponse.TrainerStatusEntry)
    })
  ,
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'status_pb2'
  # @@protoc_insertion_point(class_scope:status.StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)
_sym_db.RegisterMessage(StatusResponse.TrainerStatusEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSRESPONSE_TRAINERSTATUSENTRY._options = None
  _STATUSRESPONSE_TRAINERSTATUSENTRY._serialized_options = b'8\001'
  _STATUSENUM._serialized_start=378
  _STATUSENUM._serialized_end=487
  _STATUS._serialized_start=24
  _STATUS._serialized_end=62
  _STATUSREQUEST._serialized_start=64
  _STATUSREQUEST._serialized_end=94
  _STATUSRESPONSE._serialized_start=97
  _STATUSRESPONSE._serialized_end=376
  _STATUSRESPONSE_TRAINERSTATUSENTRY._serialized_start=308
  _STATUSRESPONSE_TRAINERSTATUSENTRY._serialized_end=376
# @@protoc_insertion_point(module_scope)
