# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trainer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'trainer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commu_pb2 as commu__pb2
import status_pb2 as status__pb2
import control_pb2 as control__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtrainer.proto\x12\x07trainer\x1a\x0b\x63ommu.proto\x1a\x0cstatus.proto\x1a\rcontrol.proto2\xb9\x01\n\x07Trainer\x12\x33\n\x04post\x12\x12.commu.PostRequest\x1a\x13.commu.PostResponse\"\x00(\x01\x12>\n\x07\x63ontrol\x12\x17.control.ControlRequest\x1a\x18.control.ControlResponse\"\x00\x12\x39\n\x06status\x12\x15.status.StatusRequest\x1a\x16.status.StatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trainer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAINER']._serialized_start=69
  _globals['_TRAINER']._serialized_end=254
# @@protoc_insertion_point(module_scope)
