# Copyright 2022 The XFL Authors. All rights reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trainer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commu_pb2 as commu__pb2
import status_pb2 as status__pb2
import control_pb2 as control__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trainer.proto',
  package='trainer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rtrainer.proto\x12\x07trainer\x1a\x0b\x63ommu.proto\x1a\x0cstatus.proto\x1a\rcontrol.proto2\xb9\x01\n\x07Trainer\x12\x33\n\x04post\x12\x12.commu.PostRequest\x1a\x13.commu.PostResponse\"\x00(\x01\x12>\n\x07\x63ontrol\x12\x17.control.ControlRequest\x1a\x18.control.ControlResponse\"\x00\x12\x39\n\x06status\x12\x15.status.StatusRequest\x1a\x16.status.StatusResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[commu__pb2.DESCRIPTOR,status__pb2.DESCRIPTOR,control__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TRAINER = _descriptor.ServiceDescriptor(
  name='Trainer',
  full_name='trainer.Trainer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=69,
  serialized_end=254,
  methods=[
  _descriptor.MethodDescriptor(
    name='post',
    full_name='trainer.Trainer.post',
    index=0,
    containing_service=None,
    input_type=commu__pb2._POSTREQUEST,
    output_type=commu__pb2._POSTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='control',
    full_name='trainer.Trainer.control',
    index=1,
    containing_service=None,
    input_type=control__pb2._CONTROLREQUEST,
    output_type=control__pb2._CONTROLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='status',
    full_name='trainer.Trainer.status',
    index=2,
    containing_service=None,
    input_type=status__pb2._STATUSREQUEST,
    output_type=status__pb2._STATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAINER)

DESCRIPTOR.services_by_name['Trainer'] = _TRAINER

# @@protoc_insertion_point(module_scope)
